version: "3.0"
services:
  web:
    image: demoapp1
    build: .
    ports:
      - "8000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_RETRY_DELAY=0.5
      - REDIS_MAX_RETRIES=5
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"